name = "cf-logger"
type = "javascript"
zone_id = ""
account_id = "0ad2c9e474036a9096bdfa9f25fa4eb2"
route = ""
workers_dev = true

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./dist/index.mjs"

[durable_objects]
bindings = [{ name = "LOGTOPIC", class_name = "LogTopic" }]